server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: findme-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: locationService
          uri: lb://FINDME-LOCATION-SERVICE
          predicates:
            - Path=/location/**
          filters:
            - RewritePath=/location/?(?<segment>.*),/$\{segment}